### ISSUE TITLE
Any way to implement a timeout when when waiting for a response?

### ISSUE THREAD

**Issue by realnsleo** [nubosoftware/node-tcp#1]
Hello,

Thank you for this package. Is there any way of setting a timeout when waiting for data from the remote server? For example:

```
try {
    await conn.writeBuffer(
        Buffer.from(`string\r\n`, 'utf8')
    )

    let data: Buffer = await NetClient.readBuffer(undefined, 5000) // timeout 5 seconds
} catch(e) {
    // catch and handle timeout error
}

```
Or perhaps is there a better way of handling an instance where there is no response  from the remote server?
Thanks.

**Comment by nubosoftware** [comment]
Good suggestion, we will add read timeout in future release.

Currently you can try to set timeout on the socket. When timeout occur, the socket will be closed  and the readBuffer throw an error:

`conn.socket.setTimeout(10000);`

**Comment by realnsleo** [comment]
@nubosoftware I am reopening this to request for guidance on how best to utilize this package. I am developing a REST API that serves clients that wish to request information about particular products. The API needs to communicate with another service via TCP to get certain information about the products. The way I designed the API is to use one TCP connection which is shared with all API requests. Something like this:

```
/* conn.ts */
const conn = await NetConn.connectToHost(options, false);
export conn;

/* controller.ts */
import conn from 'conn.ts'

await conn.socket.setTimeout(15000)
await conn.writeBuffer(Buffer.from(`string\r\n`, 'utf8'))

let data= await conn.readBuffer(undefined)
response = data.toString('utf8')

// Return data to user
return response
```

My question is:

1. Would you recommend this pattern?
2. Would you recommend to create a new tcp connection per request
3. Using the timeout above, it destroys the tcp connection and all subsequent requests hang (can a timeout be set only on read)
4. Is there a better approach you would recommend?

Thanks for taking the time to read this and I hope to hear from you soon.

Regards!

**Comment by nubosoftware** [comment]
It's not recommended to use a shared TCP connection for concurrent requests. 
If you do not want to create a new connection for each request, you can use a connection pool pattern. e.g. use [https://www.npmjs.com/package/generic-pool](generic-pool) as a connection pool

**Comment by realnsleo** [comment]
Thanks @nubosoftware. That makes sense. I will close this now. Thank you for your guidance.

**Comment by nubosoftware** [comment]
Just to update you that we added timeout implementation:
https://github.com/nubosoftware/node-tcp#timeouts

**Comment by realnsleo** [comment]
> Just to update you that we added timeout implementation: https://github.com/nubosoftware/node-tcp#timeouts

Awesome! Appreciated👍
